<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <OutputType>WinExe</OutputType>
      <TargetFramework>net6.0-windows</TargetFramework>
      <Nullable>enable</Nullable>
      <UseWindowsForms>true</UseWindowsForms>
      <PublishSingleFile>true</PublishSingleFile>
      <SelfContained>false</SelfContained>
      <PathMap>$(SolutionDir)=$(SolutionName)/</PathMap>
    </PropertyGroup>
    <ItemGroup>
      <EmbeddedResource Include="Resources\Boards\Blue\Board.png" />
      <EmbeddedResource Include="Resources\Boards\Brown\Board.png" />
      <EmbeddedResource Include="Resources\Boards\Gray\Board.png" />
      <EmbeddedResource Include="Resources\Boards\Green\Board.png" />
      <EmbeddedResource Include="Resources\Boards\Orange\Board.png" />
      <EmbeddedResource Include="Resources\Boards\Purple\Board.png" />
      <EmbeddedResource Include="Resources\Boards\Red\Board.png" />
      <EmbeddedResource Include="Resources\Buttons\Backward.png" />
      <EmbeddedResource Include="Resources\Buttons\Forward.png" />
      <EmbeddedResource Include="Resources\Buttons\Pause.png" />
      <EmbeddedResource Include="Resources\Buttons\Play.png" />
      <EmbeddedResource Include="Resources\Buttons\ToEnd.png" />
      <EmbeddedResource Include="Resources\Buttons\ToStart.png" />
      <EmbeddedResource Include="Resources\Buttons\Erase.png" />
      <EmbeddedResource Include="Resources\Buttons\Move.png" />
      <EmbeddedResource Include="Resources\Menus\Close.png" />
      <EmbeddedResource Include="Resources\Menus\Collapse.png" />
      <EmbeddedResource Include="Resources\Menus\Delete.png" />
      <EmbeddedResource Include="Resources\Menus\Down.png" />
      <EmbeddedResource Include="Resources\Menus\Expand.png" />
      <EmbeddedResource Include="Resources\Menus\Log.png" />
      <EmbeddedResource Include="Resources\Menus\Promote.png" />
      <EmbeddedResource Include="Resources\Menus\Reload.png" />
      <EmbeddedResource Include="Resources\Menus\Up.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\bb.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\bk.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\bn.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\bp.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\bq.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\br.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\wb.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\wk.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\wn.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\wp.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\wq.png" />
      <EmbeddedResource Include="Resources\Pieces\Alpha\wr.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\bb.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\bk.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\bn.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\bp.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\bq.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\br.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\wb.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\wk.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\wn.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\wp.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\wq.png" />
      <EmbeddedResource Include="Resources\Pieces\Cases\wr.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\bb.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\bk.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\bn.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\bp.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\bq.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\br.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\wb.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\wk.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\wn.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\wp.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\wq.png" />
      <EmbeddedResource Include="Resources\Pieces\Classic\wr.png" />
      <EmbeddedResource Include="Resources\Sounds\Capture.wav" />
      <EmbeddedResource Include="Resources\Sounds\GameOver.wav" />
      <EmbeddedResource Include="Resources\Sounds\Move.wav" />
    </ItemGroup>
</Project>
